services:
  ollama:
    image: ollama/ollama
    expose:
      - 11434/tcp
    runtime: nvidia
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: llama --version
    volumes:
      - ./llama:/root/.llama
      - ./entrypoint.sh:/root/entrypoint.sh
    entrypoint: ["/bin/sh", "/root/entrypoint.sh"]
    networks:
      - general

  qdrant:
    image: qdrant/qdrant
    expose:
      - 6333/tcp
      - 80/tcp
    networks:
      - general

  solution:
    container_name: solution
    runtime: nvidia
    environment:
      DEV: True
    expose:
      - 443/tcp
      - 8000/tcp
    ports:
      - "443:443"
      - "8000:8000"
    build:
      context: .
      dockerfile: app/Dockerfile
    dns:
      - "1.1.1.1"
    depends_on:
      - ollama
    command: [ "/bin/sh", "-c", "python3.12 app/bot/__main__.py" ]
    networks:
      - general



networks:
  general:
    driver: bridge
